import { first } from "./fonts"

export const metadata = {
  title: 'WebWeaverDev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"></link>
      </head>
      <body className={first.className}>{children}</body>
    </html>
  )
}
